# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersdata',
            name='email',
            field=models.EmailField(default='Dj@eg.com', max_length=255),
        ),
    ]
