# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 22:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='soil_moisture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_level', models.FloatField(default=0.0)),
                ('dt', models.DateTimeField(default=datetime.datetime(2017, 10, 7, 4, 15, 59, 585322))),
            ],
        ),
        migrations.CreateModel(
            name='temp_read',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.FloatField(default=0.0)),
                ('dt', models.DateTimeField(default=datetime.datetime(2017, 10, 7, 4, 15, 59, 554087))),
            ],
        ),
        migrations.CreateModel(
            name='water_level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.FloatField(default=0.0)),
                ('is_on', models.CharField(choices=[('1', 'YES'), ('0', 'OFF')], max_length=3)),
            ],
        ),
    ]
