# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-07 00:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20171005_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soil_moisture',
            name='dt',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 7, 6, 23, 36, 504457)),
        ),
        migrations.AlterField(
            model_name='soil_moisture',
            name='m_level',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='temp_read',
            name='dt',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 7, 6, 23, 36, 489384)),
        ),
        migrations.AlterField(
            model_name='temp_read',
            name='temp',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='water_level',
            name='level',
            field=models.CharField(max_length=5),
        ),
    ]
